### ISSUE TITLE
About the evaluation

### ISSUE THREAD

**Issue by hqyang** [thu-coai/CDial-GPT#1]
May I get the evaluation code?  The BLUE-2 score is 67.2 for Transformer and 66.3 for GPTLCCC-large, respectively.  It seems that the performance is so amazing.  How can it be attained? Thanks.

**Comment by lemon234071** [comment]
> May I get the evaluation code? The BLUE-2 score is 67.2 for Transformer and 66.3 for GPTLCCC-large, respectively. It seems that the performance is so amazing. How can it be attained? Thanks.

Thank you for pointing that. 
Sorry for forgetting to mention that we multiplied the BLEU by 1000. We used the NLTK toolkit to compute the BLEU.
In term of dist and embedding metrics we multiplied 100.
We will revise the problem.
