### ISSUE TITLE
超过512字符未自动进行截断

### ISSUE THREAD

**Issue by natureLanguageQing** [thu-coai/CDial-GPT#11]
本地选了一个单轮对话的数据集，数据集部分样本长度超过512长度。在训练过程中会出现RuntimeError: index out of range: Tried to access index 513 out of table with 512 rows. at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
的错误。希望代码可以训练过程中自动截断。

**Comment by lemon234071** [comment]
感谢您的建议，我们在清洗数据的时候对数据进行了长度限制，我们后续会在代码中加入该功能。

**Comment by natureLanguageQing** [comment]
还有就是数据加载部分的预处理，这个我觉得咱们可以上最大线程数同时处理这个。会提升很多的速度。我们有意向贡献数据集，可以配合一下吗？微信 15246115202

**Comment by lemon234071** [comment]
> 还有就是数据加载部分的预处理，这个我觉得咱们可以上最大线程数同时处理这个。会提升很多的速度。我们有意向贡献数据集，可以配合一下吗？微信 15246115202

继承的pytorch 的Dataset 类中可以通过设置num_workers参数来控制加载数据的线程。稍后加您微信。
