### ISSUE TITLE
请问如何从头开始训练模型

### ISSUE THREAD

**Issue by 17702513221** [thu-coai/CDial-GPT#13]
由于我希望用来训练语音识别的语言模型，希望可以从头开始训练，请问应该输入哪个命令
python3 train.py --data_path data/toy_data.json
报错
AttributeError: 'SummaryWriter' object has no attribute 'logdir'

**Comment by lemon234071** [comment]
> 由于我希望用来训练语音识别的语言模型，希望可以从头开始训练，请问应该输入哪个命令
> python3 train.py --data_path data/toy_data.json
> 报错
> AttributeError: 'SummaryWriter' object has no attribute 'logdir'

从头训练不指定 "--pretrained" 即可， 上述报错可能是由于tensorboard版本所致。

**Comment by Tylerjoe** [comment]
@17702513221 请问你找不到logdir的问题怎么解决的呢
