### ISSUE TITLE
The main difference with chitchat

### ISSUE THREAD

**Issue by xiejiachen** [thu-coai/CDial-GPT#16]
What is the key theory difference with https://github.com/yangjianxin1/GPT2-chitchat

**Comment by silverriver** [comment]
Unfortunately, there is no key theory difference.

Acturally, there is no key theory difference between almost all the GPT2 pre-training model.

Maybe the major difference that disinguish our project is the data filtering pipeline and massive amont of dialogue data we have proposed.
