### ISSUE TITLE
How  to  select the most appropriate response with some ranking strategies ?

### ISSUE THREAD

**Issue by huangdacheng** [thu-coai/CDial-GPT#18]
How  to  select the most appropriate response with some ranking strategies ?
Any good ideas for advice?

**Comment by silverriver** [comment]
I think the strategy provided in this paper works pretty well.

A Diversity-Promoting Objective Function for Neural Conversation Models

**Comment by huangdacheng** [comment]
Thanks for the recommendation. But other question, any better evaluation  criterion to estimate the model. I think BLEU is not suitable for  open-domain conversation.


> I think the strategy provided in this paper works pretty well.
> 
> A Diversity-Promoting Objective Function for Neural Conversation Models

**Comment by lemon234071** [comment]
> Thanks for the recommendation. But other question, any better evaluation criterion to estimate the model. I think BLEU is not suitable for open-domain conversation.
> 
> > I think the strategy provided in this paper works pretty well.
> > A Diversity-Promoting Objective Function for Neural Conversation Models

The manual evaluation would be better. As far as I know, there is currently no good automatic metric.

**Comment by huangdacheng** [comment]
Thank you . 看论文，我理解A Diversity-Promoting Objective Function for Neural Conversation Models是打压无意思的回复，如I don't know.
其实我们现在遇到另一个问题，就是生成的responses都是有信息量的句子，但怎么样避免选出的句子是一本正常的胡说八道呢?

**Comment by lemon234071** [comment]
> Thank you . 看论文，我理解A Diversity-Promoting Objective Function for Neural Conversation Models是打压无意思的回复，如I don't know.
> 其实我们现在遇到另一个问题，就是生成的responses都是有信息量的句子，但怎么样避免选出的句子是一本正经的胡说八道呢?

likelihood 解码：可以尝试greedy search, beam search

**Comment by lemon234071** [comment]
> > Thank you . 看论文，我理解A Diversity-Promoting Objective Function for Neural Conversation Models是打压无意思的回复，如I don't know.
> > 其实我们现在遇到另一个问题，就是生成的responses都是有信息量的句子，但怎么样避免选出的句子是一本正经的胡说八道呢?
> 
> likelihood 解码：收紧beam search 的beam size。
> sampling 解码：降低温度，收紧top-*采样阈值。

**Comment by lemon234071** [comment]
> Thank you . 看论文，我理解A Diversity-Promoting Objective Function for Neural Conversation Models是打压无意思的回复，如I don't know.
> 其实我们现在遇到另一个问题，就是生成的responses都是有信息量的句子，但怎么样避免选出的句子是一本正经的胡说八道呢?

likelihood 解码：收紧beam search 的beam size。
sampling 解码：降低温度，收紧top-*采样阈值。
