### ISSUE TITLE
您好，非常开心能看到中文预训练 GPT2 的发布，请问，您们训这个 GPT2 使用的自己构建的字典，还是用的 bert 的字典呢？

### ISSUE THREAD

**Issue by wulaoshi** [thu-coai/CDial-GPT#19]
谢谢

**Comment by lemon234071** [comment]
> 谢谢

您好，目前的模型使用的自己构建的字典， 后续V2版本会release使用bert字典训练的模型。

**Comment by wulaoshi** [comment]
> > 谢谢
> 
> 您好，目前的模型使用的自己构建的字典， 后续V2版本会release使用bert字典训练的模型。

非常期待，请问 v2 版本什么时候 发布？

**Comment by lemon234071** [comment]
> > > 谢谢
> > 
> > 
> > 您好，目前的模型使用的自己构建的字典， 后续V2版本会release使用bert字典训练的模型。
> 
> 非常期待，请问 v2 版本什么时候 发布？

这个可能需要一些时间，因为收集数据和训练模型都比较耗时。
