### ISSUE TITLE
关于分布式代码问题

### ISSUE THREAD

**Issue by xyanggu** [thu-coai/CDial-GPT#20]
你好，在train.py中引用的包是
`from torch.nn.parallel import DataParallel`
是否引用错误，应该引用为
`from torch.nn.parallel import DistributedDataParallel`

我看代码中关于分布式的代码包括了 init_process_group、加载数据的DistributedSampler等

**Comment by lemon234071** [comment]
> 你好，在train.py中引用的包是
> `from torch.nn.parallel import DataParallel`
> 是否引用错误，应该引用为
> `from torch.nn.parallel import DistributedDataParallel`
> 
> 我看代码中关于分布式的代码包括了 init_process_group、加载数据的DistributedSampler等

您好这个跟pytorch 版本有关，本repo提供代码 DistributedDataParallel 类速度会慢。

**Comment by silverriver** [comment]
@xyanggu 是的，这个问题在训练模型的时候已修复，我们没有及时更新repo中的代码。我们会对repo中的代码进行修正。谢谢您的指正。
