### ISSUE TITLE
在不同机器训练和交互的问题

### ISSUE THREAD

**Issue by coranholmes** [thu-coai/CDial-GPT#23]
训练是在有GPU的机器上做的（ubuntu20.04），微调完运行interact.py载入我自己训练的模型没问题可以聊天……
部署的时候把训练好的模型和interact.py放到了另一台机器上（windows 10）……在部署机上载入你们预训练好的模型那个LCCD_GPT没问题可以聊天，但是载入我自己训练的模型文件会报以下错误（训练机和部署机的tensorflow版本都是1.14.0没有用tf2呀）：
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 's\n_rebui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1037, in frombuf
    chksum = nti(buf[148:156])
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 2301, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 626, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: .\data\Oct07_17-06-42_xxx\pytorch_model.bin is a zip archive (did you mean to use torch.jit.load()?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\bot_gpt.py", line 148, in <module>
    model = model_class.from_pretrained(args.model_checkpoint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 629, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```
请问是怎么回事呢？想问下你们预训练的模型和我们微调完的模型是有什么不一样的地方吗？

**Comment by coranholmes** [comment]
啊，似乎是pytorch版本的问题……我再研究一下看看……

**Comment by lemon234071** [comment]
> 训练是在有GPU的机器上做的（ubuntu20.04），微调完运行interact.py载入我自己训练的模型没问题可以聊天……
> 部署的时候把训练好的模型和interact.py放到了另一台机器上（windows 10）……在部署机上载入你们预训练好的模型那个LCCD_GPT没问题可以聊天，但是载入我自己训练的模型文件会报以下错误（训练机和部署机的tensorflow版本都是1.14.0没有用tf2呀）：
> 
> ```
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 187, in nti
>     n = int(s.strip() or "0", 8)
> ValueError: invalid literal for int() with base 8: 's\n_rebui'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 2289, in next
>     tarinfo = self.tarinfo.fromtarfile(self)
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1095, in fromtarfile
>     obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1037, in frombuf
>     chksum = nti(buf[148:156])
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 189, in nti
>     raise InvalidHeaderError("invalid header")
> tarfile.InvalidHeaderError: invalid header
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 555, in _load
>     return legacy_load(f)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 466, in legacy_load
>     with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1591, in open
>     return func(name, filemode, fileobj, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1621, in taropen
>     return cls(name, mode, fileobj, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1484, in __init__
>     self.firstmember = self.next()
>   File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 2301, in next
>     raise ReadError(str(e))
> tarfile.ReadError: invalid header
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 626, in from_pretrained
>     state_dict = torch.load(resolved_archive_file, map_location="cpu")
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 386, in load
>     return _load(f, map_location, pickle_module, **pickle_load_args)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 559, in _load
>     raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
> RuntimeError: .\data\Oct07_17-06-42_xxx\pytorch_model.bin is a zip archive (did you mean to use torch.jit.load()?)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".\bot_gpt.py", line 148, in <module>
>     model = model_class.from_pretrained(args.model_checkpoint)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 629, in from_pretrained
>     "Unable to load weights from pytorch checkpoint file. "
> OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
> ```
> 
> 请问是怎么回事呢？想问下你们预训练的模型和我们微调完的模型是有什么不一样的地方吗？

您好，载入模型的代码都是Transformer库中的，同样的代码模型是同样的，没有不一样的地方。
您换了环境，我个人猜想还是跟环境有关系，不妨从这个地方入手，看看库的版本是否一致。

**Comment by coranholmes** [comment]
确实是版本的问题，pytorch版本不能低于1.6。
