### ISSUE TITLE
Can't download GPT_LCCC-large.zip

### ISSUE THREAD

**Issue by williamchai** [thu-coai/CDial-GPT#24]
```<Error>
<Code>AccessDenied</Code>
<Message>You do not have read permission on this object.</Message>
<RequestId>5F7F9DC53ADDB93530C41430</RequestId>
<HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
</Error>```

**Comment by lemon234071** [comment]
> ```
> <Code>AccessDenied</Code>
> <Message>You do not have read permission on this object.</Message>
> <RequestId>5F7F9DC53ADDB93530C41430</RequestId>
> <HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
> </Error>```
> ```

I just test all the download URLs in README, it works for me. Could you provide the failed URL address?

**Comment by williamchai** [comment]
> > ```
> > <Code>AccessDenied</Code>
> > <Message>You do not have read permission on this object.</Message>
> > <RequestId>5F7F9DC53ADDB93530C41430</RequestId>
> > <HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
> > </Error>```
> > ```
> 
> I just test all the download URLs in README, it works for me. Could you provide the failed URL address?

```
$ wget https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
--2020-10-08 21:00:14--  https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
Resolving coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)... 59.110.190.50
Connecting to coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)|59.110.190.50|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-10-08 21:00:16 ERROR 403: Forbidden.
```

**Comment by lemon234071** [comment]
> > > ```
> > > <Code>AccessDenied</Code>
> > > <Message>You do not have read permission on this object.</Message>
> > > <RequestId>5F7F9DC53ADDB93530C41430</RequestId>
> > > <HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
> > > </Error>```
> > > ```
> > 
> > 
> > I just test all the download URLs in README, it works for me. Could you provide the failed URL address?
> 
> ```
> $ wget https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> --2020-10-08 21:00:14--  https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> Resolving coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)... 59.110.190.50
> Connecting to coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)|59.110.190.50|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2020-10-08 21:00:16 ERROR 403: Forbidden.
> ```

This is the old URL, are you sure you got it from the latest README page?

**Comment by lemon234071** [comment]
> > > > ```
> > > > <Code>AccessDenied</Code>
> > > > <Message>You do not have read permission on this object.</Message>
> > > > <RequestId>5F7F9DC53ADDB93530C41430</RequestId>
> > > > <HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
> > > > </Error>```
> > > > ```
> > > 
> > > 
> > > I just test all the download URLs in README, it works for me. Could you provide the failed URL address?
> > 
> > 
> > ```
> > $ wget https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> > --2020-10-08 21:00:14--  https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> > Resolving coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)... 59.110.190.50
> > Connecting to coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)|59.110.190.50|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2020-10-08 21:00:16 ERROR 403: Forbidden.
> > ```
> 
> This is the old URL, are you sure you got it from the latest README page?

I got it, that is i forgot to update the quickstart URL, I will fix it now.

**Comment by lemon234071** [comment]
> > > ```
> > > <Code>AccessDenied</Code>
> > > <Message>You do not have read permission on this object.</Message>
> > > <RequestId>5F7F9DC53ADDB93530C41430</RequestId>
> > > <HostId>coai-dataset.oss-cn-beijing.aliyuncs.com</HostId>
> > > </Error>```
> > > ```
> > 
> > 
> > I just test all the download URLs in README, it works for me. Could you provide the failed URL address?
> 
> ```
> $ wget https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> --2020-10-08 21:00:14--  https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip
> Resolving coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)... 59.110.190.50
> Connecting to coai-dataset.oss-cn-beijing.aliyuncs.com (coai-dataset.oss-cn-beijing.aliyuncs.com)|59.110.190.50|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2020-10-08 21:00:16 ERROR 403: Forbidden.
> ```

The download URLs are updated now. Sorry for my mistake.

**Comment by williamchai** [comment]
@lemon234071 works now! Thanks for fixing!
