### ISSUE TITLE
gpt2产生的开放域的文本生成， 经常出现生成句子的有一直重复的现象，请问有什么好的办法吗

### ISSUE THREAD

**Issue by huangdacheng** [thu-coai/CDial-GPT#26]
如这个：
这首歌我一直都在听，不知道为什么，我的心好像就是一个大水坑，一直往里冲，不知道为什么，我的心就是一个大水坑，一直往里冲，不知道为什么，我的心就是一个大水坑，一直往里冲，不知道为什么，我的心就是一个大水坑

《THE CURIOUS CASE OF NEURAL TEXT DEGENERATION》 能解决这个问题吗？
我其实已经使用了 Top-p (nucleus) sampling了，但是还是经常出现上述的重复

**Comment by silverriver** [comment]
这个现象在生成式模型里面很常见。

可以考虑在解码的时候给已经解码出来的n-gram添加一些惩罚项，惩罚已经解码出来的n-gram的出现概率。
或者参考在解码的时候使用MMI等互信息增加解码多样性（https://arxiv.org/abs/1510.03055）
