### ISSUE TITLE
按照 readme 步骤进行，报错 Your PyTorch installation may be too old

### ISSUE THREAD

**Issue by HarborZeng** [thu-coai/CDial-GPT#27]
```
INFO:train.py:Build train and validation dataloaders
INFO:train.py:Load tokenized dataset from cache at dataset_cache_BertTokenizer
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    train()
  File "train.py", line 116, in train
    train_loader, val_loader, train_sampler, valid_sampler = loader_class(args, tokenizer, logger)
  File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 47, in build_dataloaders
    datasets, raw_samples = get_data(tokenizer, args.data_path, args.dataset_cache, logger)
  File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 21, in get_data
    dataset = torch.load(dataset_cache)
  File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2ad21b4193 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f2ad533c9eb in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2ad533dc04 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c6536 (0x7f2b1d66d536 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295a74 (0x7f2b1d23ca74 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #37: __libc_start_main + 0xf0 (0x7f2b24906840 in /lib/x86_64-linux-gnu/libc.so.6)
```

个人猜测可能是tensorflow版本问题吗？

**Comment by lemon234071** [comment]
> ```
> INFO:train.py:Build train and validation dataloaders
> INFO:train.py:Load tokenized dataset from cache at dataset_cache_BertTokenizer
> Traceback (most recent call last):
>   File "train.py", line 237, in <module>
>     train()
>   File "train.py", line 116, in train
>     train_loader, val_loader, train_sampler, valid_sampler = loader_class(args, tokenizer, logger)
>   File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 47, in build_dataloaders
>     datasets, raw_samples = get_data(tokenizer, args.data_path, args.dataset_cache, logger)
>   File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 21, in get_data
>     dataset = torch.load(dataset_cache)
>   File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
>     with _open_zipfile_reader(f) as opened_zipfile:
>   File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
>     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
> RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2ad21b4193 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f2ad533c9eb in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2ad533dc04 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
> frame #3: <unknown function> + 0x6c6536 (0x7f2b1d66d536 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #4: <unknown function> + 0x295a74 (0x7f2b1d23ca74 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> <omitting python frames>
> frame #37: __libc_start_main + 0xf0 (0x7f2b24906840 in /lib/x86_64-linux-gnu/libc.so.6)
> ```
> 
> 个人猜测可能是tensorflow版本问题吗？

有可能，先试试删掉现有的分词后的cache看看？

**Comment by HarborZeng** [comment]
> > ```
> > INFO:train.py:Build train and validation dataloaders
> > INFO:train.py:Load tokenized dataset from cache at dataset_cache_BertTokenizer
> > Traceback (most recent call last):
> >   File "train.py", line 237, in <module>
> >     train()
> >   File "train.py", line 116, in train
> >     train_loader, val_loader, train_sampler, valid_sampler = loader_class(args, tokenizer, logger)
> >   File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 47, in build_dataloaders
> >     datasets, raw_samples = get_data(tokenizer, args.data_path, args.dataset_cache, logger)
> >   File "/home/kingsoft/BDCI2020/CDial-GPT/od/inputters/inputter.py", line 21, in get_data
> >     dataset = torch.load(dataset_cache)
> >   File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
> >     with _open_zipfile_reader(f) as opened_zipfile:
> >   File "/home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
> >     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
> > RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
> > frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2ad21b4193 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libc10.so)
> > frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f2ad533c9eb in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
> > frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2ad533dc04 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch.so)
> > frame #3: <unknown function> + 0x6c6536 (0x7f2b1d66d536 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> > frame #4: <unknown function> + 0x295a74 (0x7f2b1d23ca74 in /home/kingsoft/anaconda3/envs/gang_gpt/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> > <omitting python frames>
> > frame #37: __libc_start_main + 0xf0 (0x7f2b24906840 in /lib/x86_64-linux-gnu/libc.so.6)
> > ```
> > 
> > 
> > 个人猜测可能是tensorflow版本问题吗？
> 
> 有可能，先试试删掉现有的分词后的cache看看？

谢谢，是cache的问题，删掉后，可以正常进入训练流程了。

**Comment by Tylerjoe** [comment]
@HarborZeng @lemon234071 请问你们的tensorflow是哪个版本的，我conda clean --all后还是这个问题，我tensorflow的版本是2.11.0
