### ISSUE TITLE
请问有数据清洗部分的代码吗？

### ISSUE THREAD

**Issue by lightcome** [thu-coai/CDial-GPT#29]

**Comment by lemon234071** [comment]
还没得空整理，后面会放出来

**Comment by lightcome** [comment]
哇，非常感谢，期待ing

**Comment by nikitacs16** [comment]
Hi
Any update regarding this?

**Comment by lemon234071** [comment]
> Hi
> Any update regarding this?

I'm afraid it will take weekends.....have something urgent.

**Comment by BeyondSelves** [comment]
感谢您的贡献和开放源码，请问数据清洗部分的代码开放过程进展得顺利吗

**Comment by lemon234071** [comment]
> 感谢您的贡献和开放源码，请问数据清洗部分的代码开放过程进展得顺利吗

不好意思之前忙别的事儿来着，之前的旧代码找不到了，最近也有一个清洗的工作，尽量今天把代码方出来吧。

**Comment by BeyondSelves** [comment]
> > 感谢您的贡献和开放源码，请问数据清洗部分的代码开放过程进展得顺利吗
> 
> 不好意思之前忙别的事儿来着，之前的旧代码找不到了，最近也有一个清洗的工作，尽量今天把代码方出来吧。

感谢同学！辛苦了~

**Comment by lemon234071** [comment]
> > > 感谢您的贡献和开放源码，请问数据清洗部分的代码开放过程进展得顺利吗
> > 
> > 
> > 不好意思之前忙别的事儿来着，之前的旧代码找不到了，最近也有一个清洗的工作，尽量今天把代码方出来吧。
> 
> 感谢同学！辛苦了~

一个粗糙的清洗代码，欢迎大家提bug和加速优化算法，以及新的清洗功能等等。
https://github.com/lemon234071/clean-dialog

**Comment by BeyondSelves** [comment]
> > > > 感谢您的贡献和开放源码，请问数据清洗部分的代码开放过程进展得顺利吗
> > > 
> > > 
> > > 不好意思之前忙别的事儿来着，之前的旧代码找不到了，最近也有一个清洗的工作，尽量今天把代码方出来吧。
> > 
> > 
> > 感谢同学！辛苦了~
> 
> 一个粗糙的清洗代码，欢迎大家提bug和加速优化算法，以及新的清洗功能等等。
> https://github.com/lemon234071/clean-dialog

同学效率真高，感谢贡献！
