### ISSUE TITLE
预测lccc数据集差异较大问题

### ISSUE THREAD

**Issue by wuzhiye7** [thu-coai/CDial-GPT#30]
使用预训练的lccc-large在lccc验证集上预测，为啥回复的f1值评估会很差呢（<0.10） 
相当于预训练模型已经看到答案了，但是预测回复与真实回复差异还是很大...

**Comment by lemon234071** [comment]
> 使用预训练的lccc-large在lccc验证集上预测，为啥回复的f1值评估会很差呢（<0.10）
> 相当于预训练模型已经看到答案了，但是预测回复与真实回复差异还是很大...

1、请问使用的什么解码方法呢？

**Comment by wuzhiye7** [comment]
> > 使用预训练的lccc-large在lccc验证集上预测，为啥回复的f1值评估会很差呢（<0.10）
> > 相当于预训练模型已经看到答案了，但是预测回复与真实回复差异还是很大...
> 
> 1、请问使用的什么解码方法呢？

默认的infer.py解码策略和topk-5 sampling 和topp-0.9 sampling 都试过

**Comment by lemon234071** [comment]
> > > 使用预训练的lccc-large在lccc验证集上预测，为啥回复的f1值评估会很差呢（<0.10）
> > > 相当于预训练模型已经看到答案了，但是预测回复与真实回复差异还是很大...
> > 
> > 
> > 1、请问使用的什么解码方法呢？
> 
> 默认的infer.py解码策略和topk-5 sampling 和topp-0.9 sampling 都试过

1、采样方法不能保证高F1, 可以尝试greedy search 或者beam search。
2、数据量大、模型基于预训练以低学习率后训练，模型不保证能记住验证集数据。

**Comment by wuzhiye7** [comment]
> > > > 使用预训练的lccc-large在lccc验证集上预测，为啥回复的f1值评估会很差呢（<0.10）
> > > > 相当于预训练模型已经看到答案了，但是预测回复与真实回复差异还是很大...
> > > 
> > > 
> > > 1、请问使用的什么解码方法呢？
> > 
> > 
> > 默认的infer.py解码策略和topk-5 sampling 和topp-0.9 sampling 都试过
> 
> 1、采样方法不能保证高F1, 可以尝试greedy search 或者beam search。
> 2、数据量大、模型基于预训练以低学习率后训练，模型不保证能记住验证集数据。

好的，感谢
