### ISSUE TITLE
关于WBDataset中标签生成的问题

### ISSUE THREAD

**Issue by Zessay** [thu-coai/CDial-GPT#35]
你好，在阅读代码的时候对于`WBDataset`这个类中的`process`这个方法存在一个疑问：

![image](https://user-images.githubusercontent.com/39905704/100821665-d09d4b80-348b-11eb-940b-f27fc6fdbd87.png)

在生成标签的时候，理论上来说应该是用前面的单词预测其下一个单词。但是，如果按照上面代码中的处理方式，所有最后一轮的单词对应的标签都是其自身了，就像下面这样：

![image](https://user-images.githubusercontent.com/39905704/100821828-1bb75e80-348c-11eb-9900-302ecb85e898.png)

和我理解的训练过程有出入，这里是否是我理解有问题呢？能够解答一下，谢谢！

**Comment by lemon234071** [comment]
Transformers库算LOSS的时候会做shift， 可看下算loss部分代码

**Comment by Zessay** [comment]
好的，谢谢！
