### ISSUE TITLE
关于数据组织方式

### ISSUE THREAD

**Issue by Hansen06** [thu-coai/CDial-GPT#36]
大佬好，请教一个问题，对于多轮对话的数据处理一直有个疑问，多轮对话在训练的时候需要拆分为多个样本吗，我看给出的示例数据好像没有分为多个样本，看代码预测的是最后一句，前面的作为context，不知道我的理解是否正确

**Comment by lemon234071** [comment]
训练的时候是需要的

**Comment by Hansen06** [comment]
所以训练是需要将多轮对话处理为多个样本的，明白了，谢谢

**Comment by Hansen06** [comment]
> 训练的时候是需要的

所以训练是需要将多轮对话处理为多个样本的，明白了，谢谢

**Comment by lemon234071** [comment]
> > 训练的时候是需要的
> 
> 所以训练是需要将多轮对话处理为多个样本的，明白了，谢谢

是的

**Comment by Tylerjoe** [comment]
所以训练多轮的时候的多轮A， B，C，D是需要拆成[[A B], [C,D]], 还是[[A B C D]]呢？谢谢
