### ISSUE TITLE
请问有没有LCCC数据集上的PPL指标

### ISSUE THREAD

**Issue by iseesaw** [thu-coai/CDial-GPT#39]
请问有没有尝试过从LCCC数据中拆分一部分出来作为验证集呢？微调后的GPT在LCCC验证集上的PPL能到达多少呢？谢谢~

**Comment by lemon234071** [comment]
> 请问有没有尝试过从LCCC数据中拆分一部分出来作为验证集呢？微调后的GPT在LCCC验证集上的PPL能到达多少呢？谢谢~

LCCC_base我们有释放 切分train valid test数据集，但是我们没有展示出各模型在上面的性能。您可以加载模型参数后自行计算在valid 或者test上的PPL。

**Comment by iseesaw** [comment]
好的，谢谢~

**Comment by li3cmz** [comment]
> 请问有没有尝试过从LCCC数据中拆分一部分出来作为验证集呢？微调后的GPT在LCCC验证集上的PPL能到达多少呢？谢谢~

你好，抱歉打扰了，可以请问下，你最终测出来的效果是怎样的吗？有测BLEU和Distinct这两个指标吗？
