### ISSUE TITLE
请问你们在LCCC pretrained后，在LCCC数据集上的指标结果是怎样的呢？

### ISSUE THREAD

**Issue by li3cmz** [thu-coai/CDial-GPT#41]
README.md里面只放了在STC数据集上的结果

**Comment by lemon234071** [comment]
Duplicate of #39 
CDial-GPT_LCCC-large 的训练数据中包含LCCC-base的测试集、验证集数据

**Comment by li3cmz** [comment]
你好，我按照 [#39](https://github.com/thu-coai/CDial-GPT/issues/39)说的，用CDial-GPT*_LCCC-base生成LCCC-base的测试集的回复，然后和对应的GT算了Bleu-2和Bleu-4，分别是2.95和0.65，请问这个是正常的吗？（结果是乘以100了的）还是我哪里没注意到呢？

**Comment by lemon234071** [comment]
要看您的解码方式、BLEU计算工具的版本、权重、平滑函数，看您的需求是否需要和我们论文中计算方式一致，稍后我找下原来的评测脚本计算一下然后贴一下我这边的计算结果吧。

**Comment by li3cmz** [comment]
> 要看您的解码方式、BLEU计算工具的版本、权重、平滑函数，看您的需求是否需要和我们论文中计算方式一致，稍后我找下原来的评测脚本计算一下然后贴一下我这边的计算结果吧。

您好呀，抱歉，因为比较急，想问下如果方便的话，是否能告诉我您使用的“解码方式、BLEU版本、权重、平滑函数”，让我自己去测下呢？

**Comment by lemon234071** [comment]
这个在论文里有说呀：温度0.7, top-p 0.9， BLEU nltk 3.4.3， 平滑函数method1， 默认权重就是BLEU4

**Comment by lemon234071** [comment]
我这里算出来的结果：

CDial-GPT_LCCC-base: 
    BLEU-2/4: 6.033, 2.317
    Dist-1/2: 0.022, 0.1904。

**Comment by li3cmz** [comment]
> 我这里算出来的结果：
> 
> CDial-GPT_LCCC-base:
> BLEU-2/4: 6.033, 2.317
> Dist-1/2: 0.022, 0.1904。

好的，十分感谢！

**Comment by li3cmz** [comment]
您好，我的bleu代码如下，nltk版本3.4.3

```
def evaluate(hyp_file_path, ref_file_path):
    with open(hyp_file_path, 'r') as f:
        hyp_words_list = [[item for item in line.strip().split()] for line in f.readlines()]
        # eg: [['你', '买单', '？'], ['我们', '有', '爱情', '么']]
        hyp_word_list = [[item for item in ''.join(reply)] for reply in hyp_words_list]
        # eg: [['你', '买', '单', '？'], ['我', '们', '有', '爱', '情', '么']]
    with open(ref_file_path, 'r') as f:
        ref_words_list = [[[item for item in line.strip().split()]] for line in f.readlines()]
        # eg: [[['相机', '今年', '木有', '回去', 'T', '.', 'T']], [['你', '过来', '我们', '什么', '关系']]]
        ref_word_list = [[[item for item in ''.join(reply)] for reply in refs] for refs in ref_words_list]
        # eg: [[['相', '机', '今', '年', '木', '有', '回', '去', 'T', '.', 'T']], [['你', '过', '来', '我', '们', '什', '么', '关', '系']]]
    
    smooth = SmoothingFunction()
    print('Calculating BLEU2(词) and BLEU4(词)...')
    bleu_2_score = corpus_bleu(ref_words_list, hyp_words_list, weights=(0.5, 0.5, 0, 0), smoothing_function=smooth.method1)
    bleu_4_score = corpus_bleu(ref_words_list, hyp_words_list, smoothing_function=smooth.method1)
    print("BLEU2(词): ", round(bleu_2_score*100, 2), "BLEU4(词): ", round(bleu_4_score*100, 2))
l
    print('Calculating BLEU2(字) and BLEU4(字)...')
    bleu_2_score = corpus_bleu(ref_word_list, hyp_word_list, weights=(0.5, 0.5, 0, 0), smoothing_function=smooth.method1)
    bleu_4_score = corpus_bleu(ref_word_list, hyp_word_list, smoothing_function=smooth.method1)
    print("BLEU2(字): ", round(bleu_2_score*100, 2), "BLEU4(字): ", round(bleu_4_score*100, 2))`
```

其中，hyp_word_list 与 ref_word_list是以字为单位去计算bleu。
它们具体内容格式见上面代码的注释部分（“eg”，这些例子，分别对应LCCC-base_test中第一、二个的gt_response和predict_response）。



git clone代码后，我按照官方给的代码，为LCCC-base的test集合生成回复。命令如下：
```
python infer.py --model_checkpoint CDial-GPT_LCCC-base/ --datapath data/LCCC-base_test.json --out_path LCCC_result.txt --top_p 0.9 --temperature 0.7
```

最终我计算得到的字级别的BLEU-2和BLEU-4分别是4.13和1.13
![image](https://user-images.githubusercontent.com/32973240/102894721-7f86e300-449e-11eb-9e92-34ab325df612.png)

想问下是否方便提供下测试脚本呢？

**Comment by lemon234071** [comment]
infer[:2]
    Out[2]: [['等', '你', '回', '来', '再', '去', '吧'], ['你', '说', '的', '对']]
    golden[:2]
    Out[3]: 
    [[['去', '相', '机', '家', '里', '吃', '…', '…']],
     [['你', '过', '来', '我', '们', '什', '么', '关', '系']]]

    from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
    nltk_bleu = []
    chencherry = SmoothingFunction()
    for i in range(4):
        weights = [1 / (i + 1)] * (i + 1)
        nltk_bleu.append(
            round(corpus_bleu(
                golden, infer, weights=weights, smoothing_function=chencherry.method1), 6))

    print('nltk BLEU', nltk_bleu)

**Comment by lemon234071** [comment]
另外因为是采样生成，随机性应该也会造成结果有所差别吧

**Comment by lemon234071** [comment]
> 我这里算出来的结果：
> 
> CDial-GPT_LCCC-base:
> BLEU-2/4: 6.033, 2.317
> Dist-1/2: 0.022, 0.1904。

抱歉我这里reference当成pair了（因为之前算STC是pair的）
更正后结果：

    nltk BLEU [0.093676, 0.042061, 0.021237, 0.011904]
    distinct [0.022, 0.1904]

脚本：
golden[:2]
Out[2]: 
[[['相', '机', '今', '年', '木', '有', '回', '去', 'T', '.', 'T']],
 [['你', '过', '来', '我', '们', '什', '么', '关', '系']]]
infer[:2]
Out[3]: [['等', '你', '回', '来', '再', '去', '吧'], ['你', '说', '的', '对']]

 from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
    nltk_bleu = []
    chencherry = SmoothingFunction()
    for i in range(4):
        weights = [1 / (i + 1)] * (i + 1)
        nltk_bleu.append(
            round(corpus_bleu(
                golden, infer, weights=weights, smoothing_function=chencherry.method1), 6))

    print('nltk BLEU', nltk_bleu)

**Comment by li3cmz** [comment]
好的，谢谢你！
