### ISSUE TITLE
为什么模型输入不用包括attention_mask呢？

### ISSUE THREAD

**Issue by li3cmz** [thu-coai/CDial-GPT#43]
你好，想问下，既然是LM，训练的时候用第n个token预测第n+1个token，那为什么不用引入attention_mask呢？这样不就使得预测n+1token的时候，已经看到了ground_truth了吗？这样的话，和测试时候的场景是不是就不一致了呢？是否训练的时候加入attention_mask，可以使得测试的效果更好点呢？

**Comment by silverriver** [comment]
训练的时候添加了future mask的。

**Comment by li3cmz** [comment]
请问具体是体现在哪里呢，我看到这里model的input是没有的。
https://github.com/thu-coai/CDial-GPT/blob/94bf1eab615b18eac28bf1e435df04d6667d8176/train.py#L129

**Comment by silverriver** [comment]
model的input中，attention_mask这个参数是限定attention不会attend到pad token上。

在transfertranfo的实现中，并没有加入attention_mask，因此我们也没有加入attention_mask这一输出。这就意味着对话模型在做self-attention的时候，是可以看到pad这个token的。（虽然按理说应该把pad这个token给完全mask掉）

至于future_mask，在model中计算attention的时候已经使用了，可以参考这里的代码
https://github.com/huggingface/transformers/blob/02e05fb0a532e572b56ba75dad6ba3db625bbdeb/src/transformers/models/gpt2/modeling_gpt2.py#L174

**Comment by li3cmz** [comment]
嗯嗯，感谢。因为我看的是OpenAIGPT，它这里确实是没有你指出的gpt2的is_cross_attention那小段代码，也就是OpenAIGPT是没有做future mask的吧

gpt2的代码：
https://github.com/huggingface/transformers/blob/02e05fb0a532e572b56ba75dad6ba3db625bbdeb/src/transformers/models/gpt2/modeling_gpt2.py#L174

OpenAIGPT的代码
https://github.com/huggingface/transformers/blob/02e05fb0a532e572b56ba75dad6ba3db625bbdeb/src/transformers/models/openai/modeling_openai.py#L176

**Comment by silverriver** [comment]
OpenAIGPT中future mask在这一行实现：

https://github.com/huggingface/transformers/blob/02e05fb0a532e572b56ba75dad6ba3db625bbdeb/src/transformers/models/openai/modeling_openai.py#L183

**Comment by li3cmz** [comment]
看到了！非常感谢~

**Comment by sau20171754** [comment]
咕咕咕GIF反腐败复古风：分不够古古怪怪股
