### ISSUE TITLE
[speaker1]/[speaker2]并没有被正确编码？

### ISSUE THREAD

**Issue by axzz** [thu-coai/CDial-GPT#44]
[speaker1]实际被BertTokenizer编码为了[、[UNK]、]三个字符

**Comment by lemon234071** [comment]
您有使用我们的vocab.txt吗？

**Comment by lemon234071** [comment]
非常抱歉，整理代码的时候疏忽了BertTokenizer这个地方，现已修正。（确认预训练时无误，预训练时使用的自己写的tokenizer类，整理代码时为方便大家使用改用的BertTokenizer）
目前处理方式：1、do_basic_tokenize=False 2、never_split=["[speaker1]", "[speaker2]"]

**Comment by lemon234071** [comment]
在代码中，speaker1 是通过以下代码编码成idx的，所以不存在被分词成 [、[UNK]、]三个字符

    bos, eos, speaker1, speaker2 = self.tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS)
