### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by Hansen06** [thu-coai/CDial-GPT#45]
大佬好，想问一下，为什么要先在中文小说数据上预训练呢，这一步的预训练是不是和对话的方式不一样

**Comment by silverriver** [comment]
因为预训练语言模型在长文本上训练得到的预训练效果会更好。

这一步的预训练方法就是一个LM。

**Comment by Hansen06** [comment]
> 因为预训练语言模型在长文本上训练得到的预训练效果会更好。
> 
> 这一步的预训练方法就是一个LM。

谢谢大佬
