### ISSUE TITLE
  loss = lm_loss / int(args.gradient_accumulation_steps) TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by Ultraman-Orb** [thu-coai/CDial-GPT#47]
(lm_loss), *_ = model(input_ids, labels=lm_labels, token_type_ids=token_type_ids)
print("lm_loss:",lm_loss)
        loss = lm_loss / int(args.gradient_accumulation_steps)
打印结果是 lm_loss:loss

**Comment by bigpo** [comment]
请问问题是怎么解决的？

**Comment by lemon234071** [comment]
> 请问问题是怎么解决的？

应该是hugginface版本的问题吧？不同版本返回的形式不一样

**Comment by bigpo** [comment]
> > 请问问题是怎么解决的？
> 
> 应该是hugginface版本的问题吧？不同版本返回的形式不一样

我刚试了下，果然是版本的问题，还请小伙伴们严格按照 requirements.txt 安装，不要懒省事 🤣
