### ISSUE TITLE
ppl 困惑度越来越大问题

### ISSUE THREAD

**Issue by Ultraman-Orb** [thu-coai/CDial-GPT#49]
在微调过程中，loss值是在不断减少，但是困惑度ppl和null是在不断增大的，epoch=1时ppl是13.765 而epoch=67时，ppl已经达到26了，为什么模型越训练困惑度越大，效果越来越不好呢？

**Comment by lemon234071** [comment]
过拟合了呗，你数据多大

**Comment by Ultraman-Orb** [comment]
> 过拟合了呗，你数据多大
我是用STC数据集微调的，627M

**Comment by lemon234071** [comment]
为啥要微调这么多个epoch

**Comment by Ultraman-Orb** [comment]
> 为啥要微调这么多个epoch

因为我看损失率一直在下降，数据量也是非常大，我就调了这么多epoch，但是有个疑问明明数据量这么大，我就一块8G显卡，batchsize是8，梯度累加是64，居然只用了10多分钟就微调了70轮，这么快是不是有问题？

**Comment by lemon234071** [comment]
肯定是的，你跟进代码进去看看，你估计是用的还是toy_data。这么多epoch肯定要好几天。那个loss显示的是训练loss，你不能根据这个判断停不停啊。。这样会过拟合滴
