### ISSUE TITLE
OpenAIGPTLMHeadModel not initialized

### ISSUE THREAD

**Issue by onexuan** [thu-coai/CDial-GPT#5]
python3 interact.py --model_checkpoint ./models/Novel_GPT/

INFO:transformers.modeling_utils:loading weights file ./models/Novel_GPT/pytorch_model.bin
INFO:transformers.modeling_utils:Weights of OpenAIGPTLMHeadModel not initialized from pretrained model: ['transformer.h.0.attn.bias', 'transformer.h.1.attn.bias', 'transformer.h.2.attn.bias', 'transformer.h.3.attn.bias', 'transformer.h.4.attn.bias', 'transformer.h.5.attn.bias', 'transformer.h.6.attn.bias', 'transformer.h.7.attn.bias', 'transformer.h.8.attn.bias', 'transformer.h.9.attn.bias', 'transformer.h.10.attn.bias', 'transformer.h.11.attn.bias']

HOW TO FIX IT

**Comment by lemon234071** [comment]
> python3 interact.py --model_checkpoint ./models/Novel_GPT/
> 
> INFO:transformers.modeling_utils:loading weights file ./models/Novel_GPT/pytorch_model.bin
> INFO:transformers.modeling_utils:Weights of OpenAIGPTLMHeadModel not initialized from pretrained model: ['transformer.h.0.attn.bias', 'transformer.h.1.attn.bias', 'transformer.h.2.attn.bias', 'transformer.h.3.attn.bias', 'transformer.h.4.attn.bias', 'transformer.h.5.attn.bias', 'transformer.h.6.attn.bias', 'transformer.h.7.attn.bias', 'transformer.h.8.attn.bias', 'transformer.h.9.attn.bias', 'transformer.h.10.attn.bias', 'transformer.h.11.attn.bias']
> 
> HOW TO FIX IT

Please check your version of the "Transformers".

**Comment by lemon234071** [comment]
> python3 interact.py --model_checkpoint ./models/Novel_GPT/
> 
> INFO:transformers.modeling_utils:loading weights file ./models/Novel_GPT/pytorch_model.bin
> INFO:transformers.modeling_utils:Weights of OpenAIGPTLMHeadModel not initialized from pretrained model: ['transformer.h.0.attn.bias', 'transformer.h.1.attn.bias', 'transformer.h.2.attn.bias', 'transformer.h.3.attn.bias', 'transformer.h.4.attn.bias', 'transformer.h.5.attn.bias', 'transformer.h.6.attn.bias', 'transformer.h.7.attn.bias', 'transformer.h.8.attn.bias', 'transformer.h.9.attn.bias', 'transformer.h.10.attn.bias', 'transformer.h.11.attn.bias']
> 
> HOW TO FIX IT

Note that,  you can not interact with Novel_GPT using interact.py!

**Comment by onexuan** [comment]
Does this mean I need to train a model myself?

**Comment by lemon234071** [comment]
> Does this mean I need to train a model myself?

I am not sure what you want to do ..., if you want a Chinese long text GPT model you can refer to https://github.com/Morizeyao/GPT2-Chinese or search it on GITHUB. Here we only provide the conversation pre-training model like [CDial-GPT](https://coai-dataset.oss-cn-beijing.aliyuncs.com/GPT_LCCC-large.zip), our "interact.py" work for this.

**Comment by onexuan** [comment]
今天刚看到你们的项目，准备测试一下interact.py，但没成功，我试了下载https://github.com/thu-coai/CDial-GPT#Pre-training的模型，但提示失败，我试了python3 interact.py --model_checkpoint ./models/Novel_GPT/

**Comment by lemon234071** [comment]
> 今天刚看到你们的项目，准备测试一下interact.py，但没成功，我试了下载[https://github.com/thu-coai/CDial-GPT#Pre-training的模型，但提示失败，我试了python3](https://github.com/thu-coai/CDial-GPT#Pre-training%E7%9A%84%E6%A8%A1%E5%9E%8B%EF%BC%8C%E4%BD%86%E6%8F%90%E7%A4%BA%E5%A4%B1%E8%B4%A5%EF%BC%8C%E6%88%91%E8%AF%95%E4%BA%86python3) interact.py --model_checkpoint ./models/Novel_GPT/

Novel_GPT是不支持的，请我们尝试 在LCCC上训练的模型。

**Comment by onexuan** [comment]
用LCCC-large 可以对话了，我再试试infer.py

**Comment by gmftbyGMFTBY** [comment]
你好，我尝试了LCCC-large可以正常对话，但是提供的LCCC-GPT2-base和LCCC-GPT-base生成的结果质量都非常差，请问是什么问题导致的呢

**Comment by lemon234071** [comment]
> 你好，我尝试了LCCC-large可以正常对话，但是提供的LCCC-GPT2-base和LCCC-GPT-base生成的结果质量都非常差，请问是什么问题导致的呢

GPT-base，GPT2-base训练的数据量都较小，GPT-base 训练数据更为干净。
GPT2-base只是为了用来比较，他的部分参数是从0初始化的。
所以还是建议使用GPT-large。
