### ISSUE TITLE
[speaker1],[speaker2] BertTokenizer 问题

### ISSUE THREAD

**Issue by yewang01** [thu-coai/CDial-GPT#57]
你好，
1.
transformers 2.1.1 版本（你们项目依赖的版本）的 BertTokenizer 是有 bug 的，即使加入
1、do_basic_tokenize=False 2、never_split=["[speaker1]", "[speaker2]"]
这两个参数，还是会错误的切分成 [, [UNK], ]。
直到 Release: v3.0.0 才修复这个 bug。
参考：https://github.com/huggingface/transformers/pull/4723

2.
直接升级 transformers 库到最新版本，会引入新的问题，因为他们 OpenAIGPTLMHeadModel 这个类的 api ，相较于 2.1.1 版本发生了变化，原来返回一个 tuple，现在返回一个类 `CausalLMOutput`，导致train.py 在运行时会报错。
参考：https://github.com/huggingface/transformers/blob/447808c85f0e6d6b0aeeb07214942bf1e578f9d2/src/transformers/models/openai/modeling_openai.py

================
非常抱歉，整理代码的时候疏忽了BertTokenizer这个地方，现已修正。（确认预训练时无误，预训练时使用的自己写的tokenizer类，整理代码时为方便大家使用改用的BertTokenizer）
目前处理方式：1、do_basic_tokenize=False 2、never_split=["[speaker1]", "[speaker2]"]

_Originally posted by @lemon234071 in https://github.com/thu-coai/CDial-GPT/issues/44#issuecomment-751961047_

**Comment by lemon234071** [comment]
非常感谢您的宝贵提示，我们将会查看该问题。在原来的token ids 构建中我们通过以下方式编码的 speaker id，训练以及生成过程中似乎没有涉及到使用tokenizer来 编码speaker id的情况。

    bos, eos, speaker1, speaker2 = self.tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS)

**Comment by yewang01** [comment]
> 非常感谢您的宝贵提示，我们将会查看该问题。在原来的token ids 构建中我们通过以下方式编码的 speaker id，训练以及生成过程中似乎没有涉及到使用tokenizer来 编码speaker id的情况。
> 
> ```
> bos, eos, speaker1, speaker2 = self.tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS)
> ```
是的，你们训练的脚本 train.py 和 interact.py 看起来都是用你说的方法构造的数据；但是，infer.py 的代码中，第 149 行定义的 function tokenize 中使用了 tokenizer.tokenize；不知道这部分是不是对该脚本执行的任务会有所影响。

**Comment by yewang01** [comment]
> > 非常感谢您的宝贵提示，我们将会查看该问题。在原来的token ids 构建中我们通过以下方式编码的 speaker id，训练以及生成过程中似乎没有涉及到使用tokenizer来 编码speaker id的情况。
> > ```
> > bos, eos, speaker1, speaker2 = self.tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS)
> > ```
> 
> 是的，你们训练的脚本 train.py 和 interact.py 看起来都是用你说的方法构造的数据；但是，infer.py 的代码中，第 149 行定义的 function tokenize 中使用了 tokenizer.tokenize；不知道这部分是不是对该脚本执行的任务会有所影响。

哦，应该没有影响的。

**Comment by lemon234071** [comment]
> > 非常感谢您的宝贵提示，我们将会查看该问题。在原来的token ids 构建中我们通过以下方式编码的 speaker id，训练以及生成过程中似乎没有涉及到使用tokenizer来 编码speaker id的情况。
> > ```
> > bos, eos, speaker1, speaker2 = self.tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS)
> > ```
> 
> 是的，你们训练的脚本 train.py 和 interact.py 看起来都是用你说的方法构造的数据；但是，infer.py 的代码中，第 149 行定义的 function tokenize 中使用了 tokenizer.tokenize；不知道这部分是不是对该脚本执行的任务会有所影响。

应该不会，通常来说，数据中不会包含该特殊字符，该字符的拼接会在build_input_from_segments中进行。 至于如果数据中果真包含该特殊字符以表示其他含义的情况，我感觉应考虑以特殊方式处理，这和BERT中的 [SEP] 类似。
不过我们会根据您的建议，尝试修复该问题。（说实话，代码和库版本确实有些老了，hin尴尬）

**Comment by Aman-4-Real** [comment]
所以这个问题目前仍然没有解决对吗，意思是在词表中添加类似"[speaker1]"的特殊符号作为分隔符也是会有问题的吗

**Comment by yewang01** [comment]
> 所以这个问题目前仍然没有解决对吗，意思是在词表中添加类似"[speaker1]"的特殊符号作为分隔符也是会有问题的吗

直接在词表里添加，老版本的 transformers 确实会遇到切分错误的情况。[speaker1] 会被切分为 ['[', 'UNK', ']'] 三个符号。但是在新的版本进行了修复，具体是哪个版本修复的，我不记得了。

或者，可以参考一下 [TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai) 项目下的 train.py
这个是使用老版本 transformers 正确切分特殊字符的打开方式。

**Comment by Aman-4-Real** [comment]
> > 所以这个问题目前仍然没有解决对吗，意思是在词表中添加类似"[speaker1]"的特殊符号作为分隔符也是会有问题的吗
> 
> 直接在词表里添加，老版本的 transformers 确实会遇到切分错误的情况。[speaker1] 会被切分为 ['[', 'UNK', ']'] 三个符号。但是在新的版本进行了修复，具体是哪个版本修复的，我不记得了。
> 
> 或者，可以参考一下 [TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai) 项目下的 train.py
> 这个是使用老版本 transformers 正确切分特殊字符的打开方式。

如果我使用 tokenizer.add_special_tokens 添加特殊字符，词表大小应该也会对应改变导致维度不一致？请问这种情况有没有好的解决办法呢？

**Comment by Aman-4-Real** [comment]
> > 所以这个问题目前仍然没有解决对吗，意思是在词表中添加类似"[speaker1]"的特殊符号作为分隔符也是会有问题的吗
> 
> 直接在词表里添加，老版本的 transformers 确实会遇到切分错误的情况。[speaker1] 会被切分为 ['[', 'UNK', ']'] 三个符号。但是在新的版本进行了修复，具体是哪个版本修复的，我不记得了。
> 
> 或者，可以参考一下 [TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai) 项目下的 train.py
> 这个是使用老版本 transformers 正确切分特殊字符的打开方式。

好的，谢谢您
