### ISSUE TITLE
json配置文件问题

### ISSUE THREAD

**Issue by Ultraman-Orb** [thu-coai/CDial-GPT#59]
在co-ai中模型的配置文件是
{
  "afn": "gelu",
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 512,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 513,
  "n_special": 0,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "predict_special_tokens": true,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "use_bfloat16": false,
  "vocab_size": 13088
}
与该项目中的配置文件略有不同，请问用哪一个？

**Comment by lemon234071** [comment]
有什么不同？

**Comment by Ultraman-Orb** [comment]
> 有什么不同？

{
  "afn": "gelu",
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "resid_pdrop": 0.1,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 512,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 513,
  "n_special": 0,
  "vocab_size": 13088
}
这是该项目中的配置文件，少了很多

**Comment by lemon234071** [comment]
从哪个加载都是一样的，按照quick start的操作就可以，config文件夹就是给一个快速的配置查看用的

**Comment by Ultraman-Orb** [comment]
> 个加载都是一样的，按照quick st

谢谢
