### ISSUE TITLE
成功使用LCCC-Large模型

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [thu-coai/CDial-GPT#6]
您好，非常感谢你们的工作，我成功的将LCCC-Large模型加入到了[OpenDialog](https://github.com/gmftbyGMFTBY/OpenDialog)中，测试结果良好。

**Comment by lemon234071** [comment]
> 您好，非常感谢你们的工作，我成功的将LCCC-Large模型加入到了[OpenDialog](https://github.com/gmftbyGMFTBY/OpenDialog)中，测试结果良好。

感谢这位亲的反馈！您的满意我们的动力！
