### ISSUE TITLE
加入电商对话数据集E-commerical Conversation Corpus的考量

### ISSUE THREAD

**Issue by BeyondSelves** [thu-coai/CDial-GPT#60]
E-commerical Conversation Corpus这个数据集是电商领域的，而LCCC-Base和其他几个数据集都是开放域闲聊，所以E-commerical Conversation Corpus这个数据集混入是不是不太合适？

**Comment by lemon234071** [comment]
1， 数据集有经过处理 2， 私以为，既然是开放，就受话题、领域的限制，智能chatbot应可以针对任何话题 与用户进行交谈，反倒是数据越多样，鲁棒性、泛化性越好。

**Comment by BeyondSelves** [comment]
> 1， 数据集有经过处理 2， 私以为，既然是开放，就不受话题、领域的限制，智能chatbot应可以针对任何话题 与用户进行交谈，反倒是数据越多样，鲁棒性、泛化性越好。

明白了，谢谢同学！
