### ISSUE TITLE
Bleu-2问题

### ISSUE THREAD

**Issue by Ultraman-Orb** [thu-coai/CDial-GPT#61]
有个问题没看懂，为什么在ppl值小于transformer的情况下，bleu-2还是小于transformer，论文这部分只是一笔带过，没太懂

**Comment by lemon234071** [comment]
同样也没有理论支撑ppl小bleu2就要小，一些工作也分析了bleu小不一定效果就好，可以看看文中引用的论文以及其他预训练工作。
