### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'another_engine'

### ISSUE THREAD

**Issue by wakw** [thu-coai/CDial-GPT#62]
![image](https://user-images.githubusercontent.com/66064229/114837384-391b1280-9e06-11eb-8428-41cbf9433633.png)
请问缺少参数如何处理
`tb_logger.attach(evaluator, log_handler=OutputHandler(tag="validation", metric_names=list(metrics.keys()),
                                                              another_engine=trainer),
                         event_name=Events.EPOCH_COMPLETED)`

**Comment by lemon234071** [comment]
似乎是版本不对应，requirements.txt中的库版本。
另外，对应最新各类库的 代码正在抽空更新。

**Comment by Huangyajuan-123** [comment]
> 似乎是版本不对应，requirements.txt中的库版本。 另外，对应最新各类库的 代码正在抽空更新。

更新最新版本了吗
