### ISSUE TITLE
from pretrian error

### ISSUE THREAD

**Issue by atlantiswqq** [thu-coai/CDial-GPT#64]
```
from transformers import AutoTokenizer

tokenizer = AutoTokenzier.from_pretrain("thu-coai/CDial-GPT2_LCCC-base")
```

Unrecognized model in thu-coai/CDial-GPT2_LCCC-base. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: wav2vec2, convbert, led, blenderbot-small, retribert, mt5, t5, mobilebert, distilbert, albert, bert-generation, camembert, xlm-roberta, pegasus, marian, mbart, mpnet, bart, blenderbot, reformer, longformer, roberta, deberta, flaubert, fsmt, squeezebert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm-prophetnet, prophetnet, xlm, ctrl, electra, encoder-decoder, funnel, lxmert, dpr, layoutlm, rag, tapas

**Comment by lemon234071** [comment]
You should follow our instruction instead of using AutoTokenizer
