### ISSUE TITLE
使用新版本 transformers[4.8.2] load CDial-GPT2_LCCC-base 模型报错

### ISSUE THREAD

**Issue by yewang01** [thu-coai/CDial-GPT#68]
新版 transformers 库加载模型会报错，项目requirements 的版本可以正常加载。
···
m = transformers.GPT2LMHeadModel.from_pretrained('./Playground/CDial-GPT2_LCCC-base/')

RuntimeError: Error(s) in loading state_dict for GPT2LMHeadModel:
	size mismatch for transformer.h.0.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.1.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.2.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.3.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.4.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.5.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.6.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.7.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.8.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.9.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.10.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
	size mismatch for transformer.h.11.attn.bias: copying a param with shape torch.Size([1, 1, 512, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 513, 513]).
···

**Comment by Maxlinn** [comment]
同样的问题，requirements中的torch版本有些老了

**Comment by jupercn** [comment]
需要修改两个地方（two modify）：
1、Lib\site-packages\transformers\models\openai\modeling_openai.py    line 413， modify as：
         if(hasattr(config,"n_ctx")):
            self.h = nn.ModuleList([Block(config.n_ctx, config, scale=True) for _ in range(config.n_layer)])
        else:
            self.h = nn.ModuleList([Block(config.n_positions, config, scale=True) for _ in range(config.n_layer)])
2、CDial-GPT interact.py  line 81 :
       #logits, *_ = model(input_ids, token_type_ids=token_type_ids)
        ret =  model(input_ids, token_type_ids=token_type_ids)
        logits = ret["logits"][0, -1, :] / args.temperature

**Comment by Cool-tong** [comment]
新版本的transformers加载不了在老版本下保存的CDial-GPT2_LCCC-base模型，所以还是用老版本transformers吧
