### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Jyukai02** [thu-coai/CDial-GPT#72]
您好，
我在 使用命令行交互的时候遇到了错误：
interact.py文件：
Traceback (most recent call last):
  File "infer.py", line 171, in <module>
    main()
  File "infer.py", line 162, in main
    out_ids = sample_sequence(history, tokenizer, model, args)
  File "infer.py", line 93, in sample_sequence
    logits = logits[0, -1, :] / args.temperature
TypeError: string indices must be integers
谢谢！

**Comment by Aaron5210** [comment]
> 您好，
> 我在 使用命令行交互的时候遇到了错误：
> interact.py文件：
> Traceback (most recent call last):
> File "infer.py", line 171, in
> main()
> File "infer.py", line 162, in main
> out_ids = sample_sequence(history, tokenizer, model, args)
> File "infer.py", line 93, in sample_sequence
> logits = logits[0, -1, :] / args.temperature
> TypeError: string indices must be integers
> 谢谢！

同样遇到了这个问题，您解决了吗

**Comment by Aaron5210** [comment]
把报错的那一行改成

**Comment by Aaron5210** [comment]
把报错的那一行改成
outputs = model(input_ids, token_type_ids=token_type_ids) 
logits = outputs.logits
logits = logits[0, -1, :] / args.temperature
