### ISSUE TITLE
结果并没有中介绍的好

### ISSUE THREAD

**Issue by changleilei** [thu-coai/CDial-GPT#74]
按照reademe中的步骤，使用STC数据集，训练出的结果，聊几句话之后，就全是乱码了,这是什么问题呢？

INFO:transformers.modeling_utils:loading weights file runs/Sep01_11-48-28_node3/pytorch_model.bin
>>> 北京的烤鸭真好吃
师 父
>>> 你喊我师父干吗
我 和 我 的 不 会 说
>>> 别爱我，没结果
我 们
>>> 爱情就是 一场游戏
慠 簍 帙 チ 髤 员 员 ， 倒 见 了 ， 莫 蔭 瀨 匾 矟 神 若 不 用 用 ， 比 翰 鑑 雲 懠 采 疲
>>> 别学我说话
神 像 是 周 淤 龚 刊 浃 儂 骚 阯 惺 灀 捋 恆 栾 凃 ㈥ 咽 息 云 沅 嵖 魍 噶 頮 蹤 詳 蟜 細
>>>

**Comment by lemon234071** [comment]
都出乱码了。。。怀疑整个操作过程中有操作不当的地方。。。具体是哪您需要检查一下了。。

**Comment by changleilei** [comment]
确实是没有操作好，readme中的git clone https://huggingface.co/thu-coai/CDial-GPT_LCCC-large, 建议改成git lfs clone https://huggingface.co/thu-coai/CDial-GPT_LCCC-large ，这样下载下的模型不会在加载时报_pickle.UnpicklingError: invalid load key, 'v'. 的错。感谢回复！
