### ISSUE TITLE
训练的时候数据

### ISSUE THREAD

**Issue by xiao-ming-code** [thu-coai/CDial-GPT#77]
想问下训练的时候这个数据是在哪的，方便给出具体代码位置么
![F{)LMD7IRGDNA5O4D$K%5H](https://user-images.githubusercontent.com/73177290/132970720-884786a8-063a-4747-9f37-c129d00d0b16.png)

**Comment by silverriver** [comment]
训练时所用的数据均已在这个repo的README中给出下载链接。
