### ISSUE TITLE
能不能公开一下LCCC-base未分词的数据集

### ISSUE THREAD

**Issue by leecuijiao** [thu-coai/CDial-GPT#79]
您好，目前的LCCC-base-split是切词后的语料，如果直接去掉空格，英文单词的边界有问题，能给个未分词的LCCC-base数据集链接吗

**Comment by leecuijiao** [comment]
您好，目前的LCCC-base-split是切词后的语料，如果直接去掉空格，英文单词的边界有问题，能给个未分词的LCCC-base数据集链接吗

**Comment by silverriver** [comment]
抱歉因为数据清洗的过程中是基于分词后的语料进行的，没有保留未分词前的语料。
