### ISSUE TITLE
关于训练的一个细节

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [thu-coai/CDial-GPT#8]
非常感谢您的工作，我在仔细阅读您的代码和README的时候注意到，你们在训练的时候，将history部分的labels全部用[UNK]代替了，loss计算的是基于response的语言模型。
我之前也有尝试过训练GPT2的对话模型（不知道是不是数据量的问题，效果并不是特别理想，数据量是50w），不过用的是和GPT2-chitchat项目中类似的，history和response整体当作一句话来训练语言模型。

我的问题是，你们没有选择后者，单纯只计算response的语言模型是有一定的原因的么，例如只训练response的语言模型比history+response的所有语言模型一起训练更好之类的。

期待您的回复！！！

**Comment by gmftbyGMFTBY** [comment]
您好，我对训练过程同样还有一个疑问：

我注意到你们的 `lm_labels` 中使用了-1来表示uncare token，但是我看OpenAIGPTLMHead的源代码中，他们计算loss使用的CrossEntropyLoss里面并没有对ignore_index指定为-1，这一部分不是特别清楚。

**Comment by lemon234071** [comment]
> 非常感谢您的工作，我在仔细阅读您的代码和README的时候注意到，你们在训练的时候，将history部分的labels全部用[UNK]代替了，loss计算的是基于response的语言模型。
> 我之前也有尝试过训练GPT2的对话模型（不知道是不是数据量的问题，效果并不是特别理想，数据量是50w），不过用的是和GPT2-chitchat项目中类似的，history和response整体当作一句话来训练语言模型。
> 
> 我的问题是，你们没有选择后者，单纯只计算response的语言模型是有一定的原因的么，例如只训练response的语言模型比history+response的所有语言模型一起训练更好之类的。
> 
> 期待您的回复！！！

我个人理解，仅供参考昂：

**Comment by lemon234071** [comment]
> 您好，我对训练过程同样还有一个疑问：
> 
> 我注意到你们的 `lm_labels` 中使用了-1来表示uncare token，但是我看OpenAIGPTLMHead的源代码中，他们计算loss使用的CrossEntropyLoss里面并没有对ignore_index指定为-1，这一部分不是特别清楚。
> 
> 如果直接运行的话，-1的标签会导致如下的错误
> ![image](https://user-images.githubusercontent.com/27548710/91251342-cc2b0d80-e78d-11ea-8055-73e93fa75e1c.png)
> 
> 我强制在CrossEntropy中指定了ignore_index=-1之后可以成功运行了

这个好像是版本关系？我们继承的[TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai)的代码。

**Comment by gmftbyGMFTBY** [comment]
@lemon234071 非常感谢的回复，我基本明白了。

**Comment by gmftbyGMFTBY** [comment]
> > 您好，我对训练过程同样还有一个疑问：
> > 我注意到你们的 `lm_labels` 中使用了-1来表示uncare token，但是我看OpenAIGPTLMHead的源代码中，他们计算loss使用的CrossEntropyLoss里面并没有对ignore_index指定为-1，这一部分不是特别清楚。
> > 如果直接运行的话，-1的标签会导致如下的错误
> > ![image](https://user-images.githubusercontent.com/27548710/91251342-cc2b0d80-e78d-11ea-8055-73e93fa75e1c.png)
> > 我强制在CrossEntropy中指定了ignore_index=-1之后可以成功运行了
> 
> 这个好像是版本关系？我们继承的[TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai)的代码。

哦，是这样啊，我这边是在参考了您的代码 `train.py` 之后，重构了一下代码发现的这个问题。那可能确实是版本的问题，那么我在CrossEntropyLoss中指定ignore_index=-1的话也是可以的么？（稍微有一点不确定）

**Comment by lemon234071** [comment]
> > > 您好，我对训练过程同样还有一个疑问：
> > > 我注意到你们的 `lm_labels` 中使用了-1来表示uncare token，但是我看OpenAIGPTLMHead的源代码中，他们计算loss使用的CrossEntropyLoss里面并没有对ignore_index指定为-1，这一部分不是特别清楚。
> > > 如果直接运行的话，-1的标签会导致如下的错误
> > > ![image](https://user-images.githubusercontent.com/27548710/91251342-cc2b0d80-e78d-11ea-8055-73e93fa75e1c.png)
> > > 我强制在CrossEntropy中指定了ignore_index=-1之后可以成功运行了
> > 
> > 
> > 这个好像是版本关系？我们继承的[TransferTransfo](https://github.com/huggingface/transfer-learning-conv-ai)的代码。
> 
> 哦，是这样啊，我这边是在参考了您的代码 `train.py` 之后，重构了一下代码发现的这个问题。那可能确实是版本的问题，那么我在CrossEntropyLoss中指定ignore_index=-1的话也是可以的么？（稍微有一点不确定）

可以的（我没记错的话）。

**Comment by gmftbyGMFTBY** [comment]
@lemon234071 好滴好滴，非常感谢
