### ISSUE TITLE
关于预训练时小说数据的格式问题

### ISSUE THREAD

**Issue by realLINorth** [thu-coai/CDial-GPT#80]
请问一下，像小说这类长文本非问答语料在预训练时是如何处理的？input_ids 形式是 `[CLS]<speaker1>123456789[SEP]` 这样子吗？

**Comment by silverriver** [comment]
在小说这类长文本非问答语料在预训练是数据的格式如下：

[CLS]霸道总裁[SEP]

不带[speaker1] [speaker2]

**Comment by realLINorth** [comment]
那 input_ids 长度是全部设定为 512，超过就直接截断，还是一个完整的句子作为 input_ids 呢？
长文本预训练只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 是吗？
非常感谢解答！

**Comment by realLINorth** [comment]
还有几个细节问题，烦请解答：
1. 那 input_ids 长度是全部设定为 512，超过就直接截断，还是将一个完整的句子作为 input_ids 呢？
2. 长文本预训练只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 是吗？
3. 长文本预训练是否需要 eval？
4. 后续你们还会做效果更好的 CDial-GPT2 吗？
非常感谢！

**Comment by realLINorth** [comment]
还有几个细节问题，烦请解答：

1. 那 input_ids 长度是全部设定为 512，超过就直接截断，还是将一个完整的句子作为 input_ids 呢？
2. 长文本预训练只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 是吗？
3. 长文本预训练是否需要 eval？
4. 后续你们还会做效果更好的 CDial-GPT2 吗？

非常感谢！

**Comment by realLINorth** [comment]
还有几个细节问题，可以麻烦解答一下吗：

1. 那 input_ids 长度是全部设定为 512，超过就直接截断，还是将一个完整的句子作为 input_ids 呢？
2. 长文本预训练只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 是吗？
3. 长文本预训练是否需要 eval？
4. 后续你们还会做效果更好的 CDial-GPT2 吗？

非常感谢！

**Comment by ChuangqHu** [comment]
> 在小说这类长文本非问答语料在预训练是数据的格式如下：
> 
> [CLS]霸道总裁[SEP]
> 
> 不带[speaker1] [speaker2]

不过按照代码里写的，似乎是带一个<speaker1>的，这个应该没啥影响吧

**Comment by ChuangqHu** [comment]
> 还有几个细节问题，可以麻烦解答一下吗：
> 
> 1. 那 input_ids 长度是全部设定为 512，超过就直接截断，还是将一个完整的句子作为 input_ids 呢？
> 2. 长文本预训练只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 是吗？
> 3. 长文本预训练是否需要 eval？
> 4. 后续你们还会做效果更好的 CDial-GPT2 吗？
> 
> 非常感谢！

第一个问题是如何啊？
第二个问题，token_type_ids 没有给模型吗？我看代码里不是都给了么
第三个问题，预训练eval可做可不做吧？

**Comment by silverriver** [comment]
1. 长度超过就做截断
2. 是的，只需要给模型 input_ids 和 labels 这两个参数，不需要 token_type_ids 。长文本预训练本质上就是在训练一个GPT
3. 取决于你想做什么事情，建议你选取valid loss最小的ckpt应用在下游任务上。
4. 如果想要用更好的对话模型可以关注EVA系列（https://github.com/thu-coai/EVA）
