### ISSUE TITLE
LCCC-base-split不能解压

### ISSUE THREAD

**Issue by bingo789** [thu-coai/CDial-GPT#82]
unzip LCCC-base-split.zip
报错：
Archive:  LCCC-base-split.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of LCCC-base-split.zip or
        LCCC-base-split.zip.zip, and cannot find LCCC-base-split.zip.ZIP, period.

用mac也解压不了

**Comment by silverriver** [comment]
请您重新下载一下试试，可能是下载的过程中出了错
