### ISSUE TITLE
用STC数据进行fine-tune是，用哪个指标保存最好的模型

### ISSUE THREAD

**Issue by GongMingGithub** [thu-coai/CDial-GPT#83]
当使用STC.json数据集进行进行fine-tune时（train.py），使用哪个指标了评价保存最好的模型？在train.py中,就是将最后一个epoch的模型保存下来了，应该使用哪个指标来确定最好的模型呢？

**Comment by GongMingGithub** [comment]
Each model  is trained until there is no progress in validation loss.

**Comment by silverriver** [comment]
建议使用valid loss最小的那个ckpt
