### ISSUE TITLE
embedding average 计算中中文分词是如何处理的。

### ISSUE THREAD

**Issue by AI-All-Labs** [thu-coai/CDial-GPT#87]
中文和英文分词使用相同的分词方式吗?英文每个字母是一个token,中文是每个字，当做一个token？例如下图中的两种方式使用哪种呢？
![image](https://user-images.githubusercontent.com/32949741/153364497-5e9fab33-61bb-46d5-b09e-d15def31bd3e.png)

**Comment by silverriver** [comment]
中文分词使用的是jieba分词
