### ISSUE TITLE
interact为什么会出现后面无限循环的情况？如何解决呢？

### ISSUE THREAD

**Issue by jiangjyjy** [thu-coai/CDial-GPT#90]
interact为什么会出现后面无限循环的情况？如何解决呢？
>>> 怎么样
很 好
>>> 你吃的什么
我 吃 的 是 我 们 学 校 的 饭
>>> 挺不错的
你 吃 的 什 么
>>> 汉堡
你 吃 的 什 么
>>> 汉堡呀
你 吃 的 什 么
>>> 咋开始循环了
你 吃 的 什 么
>>> 你好
你 吃 的 什 么
>>> 哈哈
你 吃 的 什 么
>>>

**Comment by silverriver** [comment]
这是基于概率的文本生成模型本身的问题，经常会出现重复的情况。使用更多的数据和更大的参数量可以缓解这个问题
