### ISSUE TITLE
LCCC new link

### ISSUE THREAD

**Issue by stephenroller** [thu-coai/CDial-GPT#92]
Hi there,

I noticed y'all found a new link for LCCC yesterday (3cb579a1c2bc1b4150a640df9f6f80673d990ed8). I also found the old link died on me. I have a cache of the data though and previously it seemed like it had separate train/valid/test files, but now the new links only have one massive file.

Do you have any idea what may have happened?

Cheers

**Comment by silverriver** [comment]
Hi,

Could you please provide us a link to your cached data? It will be a great help to us.

We tried to retrieve LCCC from one of our offline server after the download link died. But we can only find the version without train/valid/test split. It will be great if we can get the cached data from the original link.

Best
Yinhe

**Comment by stephenroller** [comment]
Can you email me at lastname@fb.com and we can discuss there?

**Comment by silverriver** [comment]
We have fixed the data split issue by a deeper search on our local server. The data download links have been updated. Enjoy~
